### PR TITLE
Closes #26, #59, #60

### LINKED ISSUE #26: Add an option to move the HUD
**Is your feature request related to a problem? Please describe.**
Yes, the HUD that display whenever you are using AutoClicker from this mod or not
It kinda "in the way" with other HUDs

**Describe the solution you'd like**
Maybe an option to change the X/Y Offset

**Describe alternatives you've considered**
Similar but maybe draggable?

**Additional context**
image

### LINKED ISSUE #59: Link mod config to ModMenu
**Is your feature request related to a problem? Please describe.**
Right now, opening the mod's config screen takes up an entire key-bind which could have been used for something else.

**Describe the solution you'd like**
The config should be linked to the "open config" button in Mod Menu.

**Describe alternatives you've considered**
None

**Additional context**
None

### LINKED ISSUE #60: Changing the config text to a non json-conforming text (which can happen by accident) crashes the mod.
**Describe the bug**
Changing the config text, by manually opening the config, to a non json-conforming text (which can happen by accident) crashes the mod.

**To Reproduce**
1. Open auto-clicker-fabric.json config file
2. Deliberately make a mistake in the file, example: remove a quote (") or delete a colon (:)

**Expected behavior**
The mod should detect the error, and regenerate the config.

**What actually happens**
The mod crashes.

**Crash log**
net.fabricmc.loader.impl.FormattedException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 130 path $.rightCli{
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 130 path $.rightCli{
	at com.google.gson.Gson.fromJson(Gson.java:1241) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1075) ~[gson-2.10.1.jar:?]
	at pro.mikey.autoclicker.AutoClicker.clientReady(AutoClicker.java:90) ~[main/:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.3.9+98a7dbbb90.jar:?]
	at net.minecraft.client.MinecraftClient.handler$zif000$fabric-lifecycle-events-v1$onStart(MinecraftClient.java:4375) ~[minecraft-merged-4eb0fe4bb6-1.21-net.fabricmc.yarn.1_21.1.21+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:819) ~[minecraft-merged-4eb0fe4bb6-1.21-net.fabricmc.yarn.1_21.1.21+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:224) ~[minecraft-merged-4eb0fe4bb6-1.21-net.fabricmc.yarn.1_21.1.21+build.1-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 3 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 130 path $.rightCli{
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:539) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1256) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1075) ~[gson-2.10.1.jar:?]
	at pro.mikey.autoclicker.AutoClicker.clientReady(AutoClicker.java:90) ~[main/:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.3.9+98a7dbbb90.jar:?]
	at net.minecraft.client.MinecraftClient.handler$zif000$fabric-lifecycle-events-v1$onStart(MinecraftClient.java:4375) ~[minecraft-merged-4eb0fe4bb6-1.21-net.fabricmc.yarn.1_21.1.21+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:819) ~[minecraft-merged-4eb0fe4bb6-1.21-net.fabricmc.yarn.1_21.1.21+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:224) ~[minecraft-merged-4eb0fe4bb6-1.21-net.fabricmc.yarn.1_21.1.21+build.1-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 3 more

Process finished with exit code 1

**Minecraft Enviorment**
 - Minecraft Version: [1.21]
 - XRay Mod Version: [21.0.1]

**Additional context**
None

### PR DESCRIPTION
**Pull request by AdyTech99**
Closes #26 
Closes #59 
Closes #60 
Bumped version number.
Added a link to the "issues" tab of the modmenu.

### CODE REVIEW

**Comment by AdyTech99** [comment]
Bump.

**Comment by MichaelHillcox** [comment]
Basically any hud location that isn't top-left hides the GUI?

Other than that, looks fine to me

**Comment by AdyTech99** [comment]
It appears that large GUI scales makes the HUD disappear... it works fine on lower sizes.

**Comment by AdyTech99** [comment]
Fixed, please check

Screenshot 2024-07-21 at 19 21 46

Screenshot 2024-07-21 at 19 21 10

Screenshot 2024-07-21 at 19 21 50

Screenshot 2024-07-21 at 19 21 58

**Comment by MichaelHillcox** [comment]
Any chance of right aligning the text on the right side options?

**Comment by MichaelHillcox** [comment]
Sorry for the slow review btw, life's been super busy. Thanks for all the hard work you've been putting in :heart:

**Comment by AdyTech99** [comment]
> Any chance of right aligning the text on the right side options?

I didn't get what you mean?

**Comment by MichaelHillcox** [comment]
Basically, if it's on the right, align the text from the right meaning you don't need to guess the width of the text. There is still and issue with it overflowing the screen when placed on the right side

**Comment by AdyTech99** [comment]
I don't know how to "align the text from the right" so I just got the width of the text with TextRenderer#getWidth, and used that in my calculations.
It appears to work fine for all GUI scales, (except the text intersecting with the hotbar on the largest scale, but it seems manageable):

### Scale 4:
Screenshot 2024-07-22 at 13 06 35

### Scale 6:
Screenshot 2024-07-22 at 13 06 21

### Scale 7
Screenshot 2024-07-22 at 13 06 45

**Pull request merged**
